framework:
  secret: "%env(APP_SECRET)%"
  csrf_protection: true
  form: true
  session:
    enabled: true
    handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler
    storage_factory_id: "session.storage.factory.native"
    cookie_secure: auto
    cookie_samesite: lax
  messenger:
    reset_on_message: true
  php_errors:
    log: true

services:
  Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler:
    arguments: ["@snc_redis.session"]
