framework:
  secret: "%env(APP_SECRET)%"
  csrf_protection: true
  test: true
  session:
    handler_id: null
    cookie_secure: auto
    cookie_samesite: lax
    storage_factory_id: session.storage.factory.native
