security:
  enable_authenticator_manager: true
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
      algorithm: argon2i
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: username
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      lazy: true
      provider: app_user_provider
      custom_authenticator: App\Security\AppAuthenticator
      logout:
        path: security_logout
        target: homepage
  role_hierarchy:
    ROLE_ADMIN: ROLE_USER
  access_control:
    - { path: ^/users, roles: ROLE_ADMIN }
    # - { path: ^/tasks, roles: ROLE_USER }
    # - { path: ^/login, roles: PUBLIC_ACCESS }
    # - { path: ^/logout, roles: PUBLIC_ACCESS }
