security:
  enable_authenticator_manager: true
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"
  providers:
    users_in_memory: { memory: null }
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      lazy: true
      provider: users_in_memory
  access_control:
    # - { path: ^/users, roles: ROLE_ADMIN }
    # - { path: ^/tasks, roles: ROLE_USER }
    # - { path: ^/login, roles: PUBLIC_ACCESS }
    # - { path: ^/login_check, roles: PUBLIC_ACCESS }
    # - { path: ^/logout, roles: PUBLIC_ACCESS }
