# See https://github.com/snc/SncRedisBundle/blob/master/docs/README.md
snc_redis:
  clients:
    session:
      type: predis
      alias: session
      dsn: "%env(REDIS_URL)%"
      logging: "%kernel.debug%"
