image: jakzal/phpqa:php8.0

variables:
  TIMEOUT_SECONDS: 1

before_script:
  - composer --version
  - composer install

cache:
  paths:
    - vendor/

stages:
  - Dependencies
  - Fixes
  - PhpLint
  - TwigLint

security-checker:
  stage: Dependencies
  script:
    - local-php-security-checker composer.lock
  allow_failure: false

php-cs-fixer:
  stage: Fixes
  script:
    - php-cs-fixer fix src
  allow_failure: true

phpa:
  stage: PhpLint
  script:
    - "phpa \
      --exclude=./src/Kernel.php \
      --exclude=./src/Extensions/ \
      --exclude=./vendor/ \
      ./src"
  allow_failure: true

phpcs:
  stage: PhpLint
  script:
    - phpcs -v --standard=PSR2 --ignore=./src/Kernel.php ./src
  allow_failure: true

phpcs-security-audit:
  stage: PhpLint
  script:
    - phpcs -v --extensions=php,inc,lib,module,info --standard=Security --ignore=./src/Kernel.php ./src
  allow_failure: true

phplint:
  stage: PhpLint
  script:
    - phplint --exclude=./src/Kernel.php ./src
  allow_failure: true

phpstan:
  stage: PhpLint
  script:
    - phpstan analyse ./src
  allow_failure: true

twig-lint:
  stage: TwigLint
  script:
    - twig-lint lint ./templates
  allow_failure: true

twigcs:
  stage: TwigLint
  script:
    - twigcs ./templates
  allow_failure: true
