version: "3.7"

services:
  database:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-symfony}
      POSTGRES_USER: ${POSTGRES_USER:-symfony}
    volumes:
      - database:/var/lib/postgresql
    ports:
      - "5432"

  http:
    image: nginx:1-alpine
    depends_on:
      - php
      - node
      - host-bridge
    volumes:
      - ./docker/dev/nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public/:/srv/public/:ro

  app:
    build:
      context: ./docker/dev/h2-proxy
    depends_on:
      - http

  php:
    environment:
      - APP_ENV=dev
    build:
      context: ./docker/dev/php
    working_dir: /srv
    volumes:
      - ./:/srv/

  node:
    build:
      context: ./docker/dev/node
    working_dir: /srv
    volumes:
      - ./:/srv/

  host-bridge:
    image: iamluc/docker-hostmanager
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/hosts:/hosts

networks:
  default:
    name: local

volumes:
  database: ~
