version: "3.7"

services:
  database:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-symfony}
      POSTGRES_USER: ${POSTGRES_USER:-symfony}
    volumes:
      - database:/var/lib/postgresql:rw
    ports:
      - "5432"

  nginx:
    image: nginx:1-alpine
    depends_on:
      - php
      - node
    volumes:
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public/:/srv/public/:ro
    ports:
      - "8000:80"

  php:
    build:
      context: ./docker/php
    working_dir: /srv
    volumes:
      - ./:/srv/:rw
      - ./docker/php/config/php.ini:/usr/local/etc/php/php.ini:ro
      - ./docker/php/config/symfony.ini:/usr/local/etc/php/conf.d/symfony.ini:ro
      - ./docker/php/config/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
    expose:
      - 9000

    environment:
      APP_ENV: dev
      BLACKFIRE_SERVER_ID: ~
      BLACKFIRE_SERVER_TOKEN: ~

  node:
    environment:
      - NODE_ENV=dev
    build:
      context: ./docker/node
    working_dir: /srv
    volumes:
      - ./:/srv/

networks:
  default:
    name: local

volumes:
  database: ~
