version: "3.7"

services:
  blackfire:
    image: blackfire/blackfire:v2
    network_mode: "host"
    depends_on:
      - nginx
    env_file: ./.env.local
    environment:
      BLACKFIRE_DISABLE_LEGACY_PORT: 1

  chrome:
    image: zenika/alpine-chrome:89
    command: "chromium-browser \
      -incognito \
      --headless \
      --disable-gpu \
      --no-sandbox \
      --disable-dev-shm-usage \
      --disable-software-rasterizer \
      --remote-debugging-address=0.0.0.0 \
      --remote-debugging-port=9222"
    cap_add:
      - "SYS_ADMIN"
    expose:
      - 9222

  database:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-symfony}
      POSTGRES_USER: ${POSTGRES_USER:-symfony}
    volumes:
      - database:/var/lib/postgresql:rw
    expose:
      - 5432

  nginx:
    image: nginx:1-alpine
    depends_on:
      - php
      - node
    volumes:
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public/:/srv/public/:ro
    ports:
      - "8000:80"

  node:
    environment:
      - NODE_ENV=dev
    build:
      context: ./docker/node
    working_dir: /srv
    volumes:
      - ./:/srv/

  php:
    build:
      context: ./docker/php
    working_dir: /srv
    depends_on:
      - database
      - redis
    volumes:
      - ./:/srv/:rw
      - ./docker/php/config/php.ini:/usr/local/etc/php/php.ini:ro
      - ./docker/php/config/symfony.ini:/usr/local/etc/php/conf.d/symfony.ini:ro
      - ./docker/php/config/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
    expose:
      - 9000

  redis:
    image: redis:6.2.6-alpine
    # command: [sh, -c, "rm -f /data/dump.rdb && redis-server"] Clear redis on startup
    volumes:
      - ./var/redis/:/data:rw
      - ./docker/redis.conf:/usr/local/etc/redis/redis.conf:ro
    expose:
      - 6379

networks:
  default:
    name: local
    driver: bridge

volumes:
  database: ~
